-- MySQL Script generated by MySQL Workbench
-- mer. 27 janv. 2021 15:56:26 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bdd_site_entreprise
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bdd_site_entreprise
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdd_site_entreprise` ;
USE `bdd_site_entreprise` ;

-- -----------------------------------------------------
-- Table `bdd_site_entreprise`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdd_site_entreprise`.`customers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `zip_code` INT NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdd_site_entreprise`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdd_site_entreprise`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` LONGTEXT NOT NULL,
  `price` FLOAT NOT NULL,
  `weight` FLOAT NOT NULL,
  `picture` VARCHAR(75),
  `availability` TINYINT NOT NULL,
  `stock` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdd_site_entreprise`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdd_site_entreprise`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdd_site_entreprise`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdd_site_entreprise`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `customers_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_orders_customers`
    FOREIGN KEY (`customers_id`)
    REFERENCES `bdd_site_entreprise`.`customers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_orders_customers_idx` ON `bdd_site_entreprise`.`orders` (`customers_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `bdd_site_entreprise`.`orders_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdd_site_entreprise`.`orders_products` (
  `orders_id` INT NOT NULL,
  `products_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`orders_id`, `products_id`, `quantity`),
  CONSTRAINT `fk_orders_has_products_orders1`
    FOREIGN KEY (`orders_id`)
    REFERENCES `bdd_site_entreprise`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_has_products_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `bdd_site_entreprise`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_orders_has_products_products1_idx` ON `bdd_site_entreprise`.`orders_products` (`products_id` ASC) VISIBLE;

CREATE INDEX `fk_orders_has_products_orders1_idx` ON `bdd_site_entreprise`.`orders_products` (`orders_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `bdd_site_entreprise`.`categories_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdd_site_entreprise`.`categories_products` (
  `categories_id` INT NOT NULL,
  `products_id` INT NOT NULL,
  PRIMARY KEY (`categories_id`, `products_id`),
  CONSTRAINT `fk_categories_has_products_categories1`
    FOREIGN KEY (`categories_id`)
    REFERENCES `bdd_site_entreprise`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_categories_has_products_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `bdd_site_entreprise`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_categories_has_products_products1_idx` ON `bdd_site_entreprise`.`categories_products` (`products_id` ASC) VISIBLE;

CREATE INDEX `fk_categories_has_products_categories1_idx` ON `bdd_site_entreprise`.`categories_products` (`categories_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
